# 389. Find the Difference
# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_sum = 0
        t_sum = 0

        for ch in s:
            s_sum += ord(ch)

        for ch in t:
            t_sum += ord(ch)

        res = t_sum - s_sum
        return chr(res)

if __name__ == "__main__":
    sol = Solution()
    print(sol.findTheDifference("abcd", "abcde"))  # e
