// 389. Find the Difference
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.
import java.util.*;

class Solution {
    public char findTheDifference(String s, String t) {
        int sSum = 0;
        int tSum = 0;

        for (int i = 0; i < s.length(); i++) {
            sSum += s.charAt(i);
        }

        for (int i = 0; i < t.length(); i++) {
            tSum += t.charAt(i);
        }

        int res = tSum - sSum;
        return (char) res;
    }

    // For VS Code testing
    public static void main(String[] args) {
        Solution sol = new Solution();
        System.out.println(sol.findTheDifference("abcd", "abcde")); // e
    }
}
